#database specific configuration
spring:
  datasource:
    url: jdbc:mysql://sqlcontainer:3306/microdb
    username: root	
    password: root

#jpa specific configuration
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update			

message: Hello in testing
databaseName: Postgresql
        














